name = "schemes"
compatibility_date = "2024-01-01"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

# Environment variables should be managed in the Cloudflare Dashboard
# to avoid publication conflicts and ensure availability at the Edge.
[vars]
